/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "-apple-system", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
      colors: {
        "on-primary-container": "#14007e",
        "on-background": "#32294f",
        "secondary-fixed-dim": "#bdbeff",
        "inverse-surface": "#10062d",
        "surface-container-high": "#e8deff",
        "surface-bright": "#faf4ff",
        "tertiary-dim": "#005c3d",
        "on-error-container": "#510017",
        "primary-fixed-dim": "#8885ff",
        "inverse-on-surface": "#a296c4",
        "tertiary": "#006947",
        "on-primary-fixed-variant": "#1a0099",
        "surface-container": "#ede4ff",
        "tertiary-container": "#69f6b8",
        "primary-container": "#9795ff",
        "on-primary-fixed": "#000000",
        "surface-container-highest": "#e2d7ff",
        "error-dim": "#a70138",
        "secondary": "#4647d3",
        "error-container": "#f74b6d",
        "tertiary-fixed": "#69f6b8",
        "on-secondary-container": "#2f2ebf",
        "on-tertiary-fixed": "#00452d",
        "on-tertiary": "#c8ffe0",
        "primary-dim": "#3d30d4",
        "outline": "#7b719c",
        "surface-container-low": "#f5eeff",
        "surface-tint": "#4a40e0",
        "on-tertiary-fixed-variant": "#006544",
        "on-secondary-fixed-variant": "#3a3ac8",
        "secondary-dim": "#3939c7",
        "on-secondary": "#f4f1ff",
        "on-surface": "#32294f",
        "background": "#faf4ff",
        "on-surface-variant": "#5f557f",
        "error": "#b41340",
        "surface-dim": "#dacdff",
        "primary-fixed": "#9795ff",
        "primary": "#4a40e0",
        "on-primary": "#f4f1ff",
        "outline-variant": "#b2a6d5",
        "secondary-fixed": "#cdcdff",
        "secondary-container": "#cdcdff",
        "surface": "#faf4ff",
        "tertiary-fixed-dim": "#58e7ab",
        "surface-variant": "#e2d7ff",
        "on-error": "#ffefef",
        "on-secondary-fixed": "#160bae",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#005a3c",
        "inverse-primary": "#8582ff",
        // Keeping dark background mapping for the existing dark switch mechanism if we use generic dark:bg-dark-bg classes
        "dark-bg": "#08080C"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      backdropBlur: {
        xs: '2px',
        sm: '4px',
        DEFAULT: '16px',
        md: '24px',
        lg: '32px',
        xl: '48px',
      },
    },
  },
  plugins: [],
}
